apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectapp
  template:
    metadata:
      labels:
        app: projectapp
    spec:
      containers:
        - name: server
          image: semitaho/server
